MeeTeamIdle/MeeTeam_FrontEnd

README.md

> 
- 커밋 컨밴션 업데이트
- 
> 
> 없을 경우 작성 X
> 
> 
- 
- 
close

docs: 커밋 컨밴션 업데이트

---

src/components/Header/Header.styled.ts
src/components/Header/Header.tsx
src/components/addButton/AddButton.tsx
src/components/customSelect/CustomSelect.styled.ts
src/components/customSelect/CustomSelect.tsx
src/components/dateSelect/DateSelect.styled.ts
src/components/dateSelect/DateSelect.tsx
src/components/index.ts
src/components/infoItem/InfoItem.tsx
src/components/memberSelect/MemberSelect.styled.ts
src/components/memberSelect/MemberSelect.tsx
src/components/subtitle/Subtitle.styled.ts
src/components/tag/Tag.styled.ts
src/components/tag/Tag.tsx
src/globalStyle.css
src/pages/meeTeamCreatePage/MeeTeamCreatePage.styled.ts
src/pages/meeTeamCreatePage/MeeTeamCreatePage.tsx

> 
- 전반적인 UI를 수정했습니다!
- 몇가지 기능들도 함께 수정했습니다.
> 
> 없을 경우 작성 X
> 
> 
- 아직 모달창 부분의 디자인, 인원에 대한 디자인, 달력에 대한 디자인이 미완성이라 해당부분을 제외한 부분을 업데이트 했습니다.
- 추가로 멤버 삭제 이슈에 대한 고민을 함께 하고자 PR을 올립니다...🙏
close #7

fix: 밋팀 생성 페이지 UI 및 기능 업데이트

---

package-lock.json
package.json
src/App.tsx
src/atom.tsx
src/components/customSelect/CustomSelect.styled.ts
src/components/customSelect/CustomSelect.tsx
src/components/dateSelect/DateSelect.tsx
src/components/infoItem/InfoItem.tsx
src/pages/meeTeamCreatePage/MeeTeamCreatePage.styled.ts
src/pages/meeTeamCreatePage/MeeTeamCreatePage.tsx

> 
- 새 밋팀 생성시 필요한 유효성 검사를 구현했습니다.
- 밋팀 팀명, 범위, 밋팀 분야, 밋팀 유형, 밋팀 기간
> 
> 없을 경우 작성 X
> 
> 
- 밋팀 태그 개수, 밋팀 팀명 글자수, 밋팀 기간에 관련된 세부적인 내용은 다음 회의때 논의하고 결정할 예정입니다.
close #15

feat: 새 밋팀 생성 페이지 유효성 검사 구현

---

package-lock.json
package.json
src/atom.tsx
src/components/meeteam/main/Main.styled.ts
src/components/meeteam/main/dashBoard/DashBoard.styled.ts
src/components/meeteam/main/information/Information.styled.ts
src/components/meeteam/main/recruitment/Recruitment.styeld.ts
src/components/meeteam/main/setting/Setting.styled.ts
src/components/meeteam/menu/Menu.styled.ts
src/components/meeteam/progressBar/ProgressBar.styled.ts
src/components/meeteam/requiredInformation/RequiredInformation.styled.ts
src/components/meeteam/title/Title.styled.ts
src/components/optionMenu/OptionMenu.styled.ts
src/pages/account/Account.styled.ts
src/pages/account/schoolCertification/SchoolCertificationData.ts
src/pages/account/signUp/SignUpData.ts
src/pages/account/signUp/nickNameSetting/NickNameSettingPage.tsx
src/pages/account/validation.ts
src/pages/index.ts

- Input Validation 상수화
- 닉네임 입력 페이지 유효성 검사 UI 및 기능 추가
- **공백 없이 영어, 한글, 숫자 조합 4자 이상, 16자 이하(특수문자 `_`, `.` 만 가능)** 유효성 검사
https://github.com/MeeTeamNumdle/MeeTeam_FrontEnd/assets/89342648/594648ee-8a46-47ec-985d-bdf2bbb0f0ab
- 닉네임 입력 폼을 react-hook-form 으로 교체해놨습니다! 나머지 폼들도 다 교체 예정입니다! 공통 컴포넌트로 제작하는 것도 고려하고 있습니다
- 임의로 디자인 완성 전에 유효성 검사 UI를 적용해보았는데 어떤가요?
close

feat: 학교 정보 API 연동 및 학사 정보 입력 페이지 및 닉네임 입력 페이지 유효성 검사

---

package-lock.json
package.json
src/assets/index.ts
src/components/comment/comment/Comment.tsx
src/components/comment/comment/ReplyComment.tsx
src/components/comment/commentInput/CommentInput.tsx
src/components/comment/replyInput/ReplyInput.tsx
src/components/dateSelect/DateSelect.tsx
src/components/dateSelect/DeadlineSelect.tsx
src/components/header/Header.tsx
src/components/inputDropdown/inputRole/InputRoleForm.tsx
src/components/meeteam/card/RecruitCard.tsx
src/components/profile/image/ProfileImage.tsx
src/components/recruit/applicants/ApplicantCard.tsx
src/components/recruit/recruitDetail/titleInfo/TitleInfo.tsx
src/service/index.ts
src/types/index.ts
src/types/indexSigniture.ts
src/types/recruit/response.ts

- 프로필 이미지 공통 컴포넌트 적용
- release-1.0 에 https://github.com/MeeTeamNumdle/MeeTeam_FrontEnd/issues/71 merge 시, 빌드 에러 해결
- RecruitCard 컴포넌트 내에서 ProfileImage 컴포넌트 사용 시에 userId 가 필요해서, 파라미터에 `writerId`를 추가하고 Post 타입에 `writerId`도 함께 받아야 합니다..! 
close #101

refactor: ProfileImage 공통 컴포넌트 적용

---

.gitignore

> 
- env 파일을 수정했습니다!
> 
> 없을 경우 작성 X
> 
> 
close

chore: env 파일 수정 및 gitignore node-modules 추가

---

src/components/recruit/create/RecruitTags.tsx

> 
- 빌드 에러 수정
> 
> 없을 경우 작성 X
> 
> 
close

chore: build 에러 수정

---

src/components/header/Header.tsx
src/components/profile/image/ProfileImage.tsx
src/pages/profile/edit/ProfileEditPage.tsx

- 업로드 이미지만 전역 관리하고, 렌더링 이미지는 useState로 관리
- 헤더 이미지가 안뜨길래, 해당 부분 하는김에 같이 적용하였습니다..!
close #126

fix: 남의 프로필 이미지가 본인 이미지로 보이는 이슈 수정

---

package-lock.json
src/components/header/Header.tsx

> 
- 경로 수정 반영했습니다.
> 
> 없을 경우 작성 X
> 
> 
close

chore: 포트폴리오 관리페이지 경로 수정 반영

---

src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx
src/types/recruit/payload.ts

> 
- 상세조건 하이라이트 버그 수정
> 
> 없을 경우 작성 X
> 
> 
close

chore: 상세조건 하이라이트 버그 수정

---

src/pages/recruit/recruitPage/RecruitPage.tsx

> 
- 초기화를 눌렀을 때 동작을 변경합니다.
> 
> 없을 경우 작성 X
> 
> 
close

chore: 분야 조건 동작 변경

---

src/assets/Clip.svg
src/assets/index.ts
src/components/link/details/LinkDetails.tsx
src/pages/profile/Profile.styled.ts
src/pages/profile/details/ProfileDetailsPage.tsx

- 이름 비공개 해도 비공개 설정 안되는 이슈 해결
- 연락처, 메일 변경 UI 적용
- 연락처, 메일 미입력 시, - 표기 적용
- 학과, 학점 라벨 문구 추가
- 학점 미입력 시, - 표기 적용
- `LinkDetails` 공통 컴포넌트 이용하여 링크 UI 스타일링 추가
- 본인 상세 페이지 조회 시, 비공개 아이콘 스타일링 추가
- 본인 상세 페이지 조회 시, 정보 없는 경우 기본 메세지 스타일링 추가
제가 놓친 부분이 있다면 말씀 부탁드립니다!
close #133

fix: 프로필 상세 페이지 1차 QA 피드백 적용

---

src/pages/portfolio/management/PortfolioManagementPage.styled.ts
src/pages/portfolio/management/PortfolioManagmentPage.tsx

- 포트폴리오 목록 안보이는 이슈 해결
- 포트폴리오 목록 최대 4열로 제한
제가 놓친 부분이 있다면 말씀 부탁드립니다!
close #135

fix: 포트폴리오 관리 페이지 1차 QA 피드백 적용

---

src/components/recruit/applicants/toast/Toast.styled.ts

> 
- 토스트 UI가 로컬에서만 되고 배포 사이트에서는 되지 않는 기이한 현상
https://github.com/MeeTeamNumdle/MeeTeam_FrontEnd/assets/76275691/a95561d8-fe64-4980-becc-08aa9537c920
> 
> 없을 경우 작성 X
> 
> 
close

fix: 토스트 UI 로직 및 일부 코드 변경

---

src/components/muiDatepicker/MuiDatepickerController.styled.ts
src/components/muiDatepicker/MuiDatepickerController.tsx
src/pages/profile/edit/ProfileEditPage.tsx

- useFieldArray로 이루어진 name이 formState.errors[name]으로 경로를 찾을 수 없어서,
직접 `.` 을 기준으로 name 잘라가면서 객체에 접근
close #159

fix: #159 MuiDatepickerController 유효성 검사 UI가 뜨지 않는 이슈 해결

---

src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx

> 
- 상세 조건을 클릭하자마자 하이라이트되는 버그를 수정했습니다.
> 
> 없을 경우 작성 X
> 
> 
close

fix: 상세 조건 하이라이트 버그 수정 - 배포 사이트에 적용

---

src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts

> 
- 오픈채팅방 설정 버튼 버그 수정
> 
> 없을 경우 작성 X
> 
> 
close

chore: 오픈채팅방 설정 버튼 버그 수정 - 배포 사이트 적용

---

src/service/axiosInstance.ts
src/service/recruit/applicant.ts

> 
- 신청자 관리 페이지 접근 권한 없을 때, 리다이렉션
- 백엔드에서 403 대신 400번을 준다고 하여 수연님께서 작성해주신 axiosInstance.ts에서 Error 부분에 값을 추가했습니다..!
> 
> 없을 경우 작성 X
> 
> 
- 더 필요한 부분이 있으시면 말씀해주세요!
close

feat: #140 신청자 관리 페이지 접근 권한 없을 때, 리다이렉션

---

src/pages/recruit/applierManagePage/ApplierManagePage.styled.ts

> 
- 임시로 접근권한 없는 페이지 접근 시, 로그인 페이지로 리다이렉션을 한다.
> 
> 없을 경우 작성 X
> 
> 
- 접근권한이 없는 페이지가 짧은 시간동안 뜨고, 로그인 페이지로 간다.
- 물론, 데이터를 불러오지 못해서 볼 것은 없지만, 조금 거슬린다.
close

feat: 접근권한 없는 페이지 접근 시, 로그인 페이지로 리다이렉션 - 배포 사이트 적용

---

src/components/dropdown/Dropdown.tsx

> 
- 불필요한 API 호출 횟수 감소, 로그인이 안 되어있을 경우, 게시판 -> 로그인 화면 리다이렉션 버그 수정
> 
> 없을 경우 작성 X
> 
> 
close

fix: 불필요한 API 호출 횟수 감소

---

src/pages/portfolio/management/PortfolioManagementPage.styled.ts

> 
> 
> 없을 경우 작성 X
> 
> 
close

fix: 포트폴리오 관리 페이지 버그 수정 - 배포 사이트 적용

---

src/components/dropdown/Dropdown.tsx
src/components/header/Header.tsx

> 
- 
- 
> 
> 없을 경우 작성 X
> 
> 
- 
- 
close

chore: 헤더, 필터 드랍다운 버그 수정

---

src/components/recruit/create/detailedInformation/DetailedInformation.tsx
src/components/recruit/recruitDetail/recruitDescription/RecruitDescription.styled.ts
src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx

> 
- 백엔드와 소통한 후, 텍스트 에디터의 반환값이 Object 타입이 아닌 String 타입으로 반환되어
발생하는 렌더링 이슈를 해결하였습니다.
- CSS 초기화로 인한 들여쓰기가 적용되지 않는 점도 임시로 수정하였습니다.
> 
> 없을 경우 작성 X
> 
> 
close

fix: 텍스트 에디터 string 타입으로 인한 에러 수정 및 들여쓰기 반영

---

src/atom.tsx
src/components/comment/comment/Comment.tsx
src/components/comment/comment/ReplyComment.tsx
src/components/comment/replyInput/ReplyInput.tsx
src/components/dropdown/Dropdown.tsx
src/components/header/Header.tsx
src/components/meeteam/card/RecruitCard.tsx
src/components/recruit/create/recruitRoles/RecruitRolesForm.tsx
src/components/recruit/recruitDetail/footer/ApplierFooter.tsx
src/components/recruit/recruitDetail/titleInfo/TitleInfo.tsx
src/hooks/useLogin.ts
src/pages/create/recruitCreatePage/RecruitCreatePage.tsx
src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx
src/service/recruit/board.ts
src/service/recruit/detail.ts

> 
- atom에 effect로 로컬스토리지에 저장되도록 했습니다.
- 댓글 멘션 제거
- 역할 삭제 버그 수정
> 
> 없을 경우 작성 X
> 
> 
close #189

fix: <긴급> 로그인 관련 버그 수정

---

src/atom.tsx
src/components/recruit/recruitDetail/modal/ApplyModal.styled.ts
src/components/recruit/recruitDetail/modal/ApplyModal.tsx
src/components/recruit/recruitDetail/modal/ConfirmModal.tsx
src/components/recruit/recruitDetail/modal/FinalModal.tsx
src/globalStyle.css
src/pages/recruit/recruitDetailPage/RecruitDetailPage.tsx
src/pages/recruit/recruitPage/RecruitPage.styled.ts

> 
- 구인 신청 모달 수정사항을 반영함.
> 
> 없을 경우 작성 X
> 
> 
- 확인해보시고 질문이 있으시면 부탁드려요!!
close #210

fix: 디자인팀 QA - (긴급) 신청 모달 수정사항 반영

---

src/pages/account/nicknameSetting/NicknameSettingPage.tsx

> 
- 네이버 회원가입 시, setLoginState이 빠졌던 것을 추가했다.

deploy: 로그인 상태 함수 추가

---

src/components/header/Header.tsx
src/hooks/index.ts
src/hooks/useProfile.ts
src/pages/account/nicknameSetting/NicknameSettingPage.tsx
src/pages/profile/edit/ProfileEditPage.tsx
src/service/user/Profile.ts

- 프로필 수정 후에 헤더 내 프로필 이미지 바뀌지 않는 이슈 해결
- 스킬 검색 후 엔터 이후에 폼 제출되는 이슈 해결
- 헤더 컴포넌트 내 프로필 이미지 조회 API 커스텀 훅 분리했습니다!
close #217

fix: 프로필 편집 페이지 UT 이슈 해결

---

src/components/header/Header.tsx
src/pages/account/signIn/SignInPage.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx

> 
- 로고 이미지와 일부 아이콘이 늦게 렌더링되는 이슈 작업

chore: 로고 이미지 fetch 우선순위 변경

---

src/service/endPoint.ts

- 이미지 업로드 위한 presignedURL -> signedURL 발급 엔드포인트 변경
- api 명세 변경사항 반영하였습니다.
close #234

feat: 이미지 업로드 위한 presignedURL -> signedURL 발급 엔드포인트 변경

---

src/components/recruit/recruitDetail/modal/needLogin/NeedLogin.styled.ts
src/pages/recruit/recruitPage/RecruitPage.styled.ts

> 
- 모바일에서 줄바꿈이 있는 현상을 발견하여 수정했습니다.

fix: 모바일용 줄바꿈 UI 수정

---

.github/release.yml
.github/workflows/release-drafter.yml

> 
- Release note의 템플릿을 자동으로 불러오도록 파일을 추가하였습니다.

deploy: github release 자동화 파일 추가

---

index.html
src/components/footer/Footer.tsx
src/components/header/Header.tsx
src/components/inputDropdown/inputRole/InputRoleForm.styled.ts
src/components/inputDropdown/inputRole/InputRoleForm.tsx
src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
src/components/tag/MeeteamTag.tsx

> 
- 밋팀 로고가 띄워지지 않는 이슈를 해결했습니다.
- 푸터에 링크가 덜 적용되어 동작하지 않던 이슈도 해결했습니다.
- 드롭다운 ux를 개선하고자 몇가지 작업을 하던 중에 일단 일부만 진행한 상황입니다.
- 구글 애널리틱스 분석을 위한 코드를 추가했습니다.
> 
> 없을 경우 작성 X
> 
> 
- 잘못된 점이 있다면 말씀해주세요!
close #258

chore: 일부 버그 수정 및 드롭다운 수정 / 웹 사이트 분석을 위한 코드 추가

---

index.html

> 
- 구글 애널리틱스 코드에 userId를 적용하여 사용자를 명확하게 구분하여 분석할 수 있도록 합니다.
> 
> 없을 경우 작성 X
> 
> 
- 질문이 있으시다면 말씀해주세요.
close #267

feat: #267 구글 애널리틱스 userId 적용

---

src/hooks/useAuth.ts
src/pages/account/nicknameSetting/NicknameSettingPage.tsx

- 닉네임 중복 체크 시, 불필요한 api 호출 이슈 해결
제가 놓친 부분이 있다면 말씀 부탁드립니다!
close #270

fix: 닉네임 중복 체크 시, 불필요한 api 호출 이슈 해결

---

src/pages/portfolio/edit/PortfolioEditPage.tsx
src/pages/profile/edit/ProfileEditPage.tsx
src/utils/checkEnterKeyDown.ts
src/utils/index.ts

- 프로필 편집 시 엔터 키 누르면 편집 폼 제출되는 이슈 해결
제가 놓친 부분이 있다면 말씀 부탁드립니다!
close #273

fix: 프로필 편집 시 엔터 키 누르면 편집 폼 제출되는 이슈 해결

---

src/components/dropdown/Dropdown.tsx
src/components/dropdown/dropdownDetail/DropdownDetail.styled.ts
src/components/dropdown/textBox/TextBox.tsx
src/components/header/Header.tsx
src/components/index.ts
src/components/inputDropdown/inputRole/InputRoleForm.tsx
src/components/meeteam/card/RecruitCard.tsx
src/components/recruit/create/ControlButtons.tsx
src/components/recruit/create/basicInformation/BasicInformation.styled.ts
src/components/recruit/create/basicInformation/containers/ContainerCourse.tsx
src/components/recruit/recruitBoard/detailedFilter/DetailedInput.tsx
src/components/tag/MeeteamTag.tsx
src/hooks/index.ts
src/hooks/useCheckDevice.ts
src/main.tsx
src/pages/account/signIn/SignInPage.tsx
src/pages/recruit/recruitCreatePage/RecruitCreatePage.styled.ts
src/pages/recruit/recruitCreatePage/RecruitCreatePage.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx
src/pages/routes/PrivateRouter.tsx

> 
- 헤더의 교내 / 교외 분리 최종 버전을 반영하였습니다.
- 입력창 UX의 깜빡임 개선과 "검색중입니다...", "검색결과가 없습니다."를 추가하였습니다.
- 버그: 밋팀 태그 안 되는 버그, 상세조건 필터 마우스 호버 효과, 
- 상세조건 드롭다운을 모바일 버전에서 임시 제거하였습니다.
- 교내 페이지에서 필터가 제대로 동작하지 않는데, 백엔드 문제여서 확인중에 있습니다.
> 
> 없을 경우 작성 X
> 
> 
- 질문이 있으시거나 잘못된 부분이 있다면 댓글 남겨주세요!
close #277

refactor: 입력창 UX 개선 및 교내/교외 분리 요청사항 반영

---

src/utils/checkEnterKeyDown.ts

Release 1.0.1

---

src/components/header/Header.styled.ts

> 
- 모바일 환경에서 헤더에 구인게시판 탭이 빠져있는 부분을 다시 활성화시켰습니다.

Release 1.0.2

---

src/components/portfolio/image/modal/PortfolioImageModal.styled.ts
src/components/portfolio/image/modal/PortfolioImageModal.tsx

- 포트폴리오 이미지 순서 변경 모달 반응형 UI 적용

feat: 반응형에 따른 PortfolioImageModal 컴포넌트 스타일링 변경

---

src/pages/recruit/recruitPage/RecruitPage.tsx

fix: 북마크 버그 수정

---

src/components/meeteam/card/RecruitCard.tsx
src/pages/recruit/recruitPage/RecruitPage.tsx

> 
- 북마크 클릭 시, 바로 적용되지 않는 문제가 있었습니다.
- 메인 페이지의 useQuery queryKey가 변경되면서 함께 수정하지 못했던 것들을 적용했습니다.
> 
> 없을 경우 작성 X
> 
> 
- 질문이나 궁금하신 점이 있다면 말씀해주세요!
close #297

fix: #297 북마크 쿼리키 전달하는 값 수정
